sudo: required

dist: xenial # Ubuntu Xenial 16.04

language: go

before_install:
  - uname -a
  - sudo apt-get -qq update
  - sudo apt-get install -y ipset
  - which ipset
  - echo PATH $PATH
  - GO111MODULE=on go get ./...

script:
- sudo -E env "PATH=$PATH" make test
